contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #bigbacter channel"
    url: https://nfcore.slack.com/channels/bigbacter
    about: Discussion about the nf-core/bigbacter pipeline
