# base image
FROM ubuntu:jammy

# metadata
LABEL base.image="ubuntu:jammy"
LABEL dockerfile.version="2"
LABEL software="BigBacter"
LABEL software.version="v1.0.0"
LABEL description="Basic Linux for Running BigBacter Scripts"
LABEL website="https://github.com/DOH-JDJ0303/bigbacter-nf"
LABEL license="Apache 2.0"
LABEL maintainer="Jared Johnson"
LABEL maintainer.email="jared.johnson@doh.wa.gov"

# prevents having to enter commands during apt-get install
ENV DEBIAN_FRONTEND=noninteractive

# install dependencies
RUN apt-get update && apt-get -y --no-install-recommends install \
    ca-certificates \
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    make \
    llvm \
    libncurses5-dev \
    libncursesw5-dev \
    libharfbuzz-dev \
    libfribidi-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev \
    xz-utils \
    tk-dev \
    libtiff-dev \
    libffi-dev \
    liblzma-dev \
    build-essential \
    bc \
    unzip \
    tar \
    gzip \
    curl \
    wget \
    r-base \
    r-base-dev \
    bzip2 \
    jq && \
    apt-get autoclean && \
    rm -rf /var/lib/apt/lists/*
    
# required R packages
RUN R -e "install.packages(c('tidyverse', 'phangorn','BiocManager', 'remotes', 'rjson'), repos='https://cran.rstudio.com/')"
RUN R -e "remotes::install_github('YuLab-SMU/treeio'); remotes::install_github('YuLab-SMU/ggtree')"